In [2]:
import numpy as np

In [19]:
lst = [1,2,3,4]
print(lst)
print(type(lst))
print("="*30)

s = np.array(5)
print(s)
print(s.ndim)
print(s.shape)
print("="*30)
v = np.array([1,2,3,4])
print(v)
print(v.ndim)
print(v.shape)
print("="*30)
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m)
print(m.ndim)
print(m.shape)
print("="*30)



[1, 2, 3, 4]
<class 'list'>
5
0
()
[1 2 3 4]
1
(4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [17]:
class student:
    def __init__(self,name):
        self._name = name

    @property
    def name(self):
        return self._name
s1 = student("mina")
s1.name

'mina'

In [30]:
vec = np.array([1,2,3,4,5,6])
print(vec.shape[0])
mat = vec.reshape((3,2))
mat

6


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
vec = np.array([1,2,3,4])
# mat = vec.reshape(vec.shape[0],1)
mat = vec.reshape(1,vec.shape[0])

print(mat)
# mat = vec.reshape((2,2))
# print(mat.shape)
# print(mat.shape[0])
# print(mat.shape[1])

[[1 2 3 4]]


In [36]:
vec = np.array([1,2,3,4])
mat = vec[:,None]
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [37]:
def array_reshape(arr,rows,cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows,cols)
    except(TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshpae operation: {e}")
    


In [39]:
vec = [1,2,3,4,5,6]
array_reshape(vec,len(vec),1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [45]:
class aaa:
    pass
o1 = aaa()
mat = np.array([[1,2,o1],
              [4,5,6.5],
              [7,8,9]])
print(mat.dtype)
print(mat)

object
[[1 2 <__main__.aaa object at 0x000001F7E42A73B0>]
 [4 5 6.5]
 [7 8 9]]


In [50]:
class aaa:
    pass
o1 = aaa()
mat = np.array([[3.5,2,3],
              [4,5,6.5],
              [7,8,9]])
fmat = mat.astype(int)
print(fmat)
print(fmat.dtype)
print(mat.dtype)
print(mat)

[[3 2 3]
 [4 5 6]
 [7 8 9]]
int64
float64
[[3.5 2.  3. ]
 [4.  5.  6.5]
 [7.  8.  9. ]]


In [51]:
def convert_dtype(arr,dtype):
    try:
        arr = np.array(arr)
        return arr.astype(dtype)
    except TypeError as e:
        raise TypeError(f"invalid target data type: {dtype}") from e


In [ ]:
v = np.array([1,2,3,5,1])
print(v[3])

mat = np.array([[3.5,2,3],
              [4,5,6.5],
              [7,8,9]])
print(mat[1,2])
print(mat[1:2,0:2])


5
6.5
[[4. 5.]]


In [60]:
mat = np.array([[3.5,2,3],
              [4,5,6.5],
              [7,8,9]])

mat = mat.T
print(mat)

[[3.5 4.  7. ]
 [2.  5.  8. ]
 [3.  6.5 9. ]]


In [65]:
mat = np.zeros((3,4))
print(mat)
mat = np.ones((3,4))
print(mat)
mat = np.full((3,4),6)
print(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [69]:
def init_arr(shape,value=0):
    return np.full(shape,value)

zeros = init_arr((3,4))
print(zeros)
ones = init_arr((3,4),1)
print(ones)
seven = init_arr((3,4),7)
print(seven)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
